### ISSUE TITLE
Create a chat channel

### ISSUE THREAD

**Issue by jawahar273** [a-mma/AquilaDB#18]

**Comment by freakeinstein** [comment]
Hi @jawahar273 That seems a good idea. We have been thinking about it for a while. But the community was not matured. Still we're not sure if it's the right time. But we have decided to give it a push. Let us find the right channel - if you have a suggestion please share with us. We hearty welcome any help from you set it up and keep it driving.

**Comment by freakeinstein** [comment]
Created Discord chatroom at https://discord.gg/5YP7zHS

Closing.
