### ISSUE TITLE
Is there any gpu acceleration for AquilaDB ? 

### ISSUE THREAD

**Issue by pasa13142** [a-mma/AquilaDB#51]
Firstly, I want to say thanks for this project to you,

I am looking for gpu acceleration for AquilaDB, because I think its build on faiss, so may have gpu acceleration?

Does aquilaDB has gpu acc ?

**Comment by freakeinstein** [comment]
@pasa13142  Not yet. Because we use Annoy for indexing data below 10000 which doesn't support GPU. So, as of now it's not possible to enable GPU for FAISS only. I's a good suggestion. Sure looking forward to an implementation possibility.

**Comment by pasa13142** [comment]
Thank you, I believe you do the best !
