### ISSUE TITLE
docker command not working

### ISSUE THREAD

**Issue by sreelekshmyselvin** [a-mma/AquilaDB#63]
I was trying to install AquilaDB using the docker file. I tried the following command 

**docker build -t ammaorg/aquiladb:latest .**

It was showing the following error 

**unable to prepare context: unable to evaluate symlinks in Dockerfile path**

**Comment by akvish** [comment]
Check docker file is present in the current directory

**Comment by freakeinstein** [comment]
@sreelekshmyselvin Thanks for reporting the issue. Please specify the dockerfile with `-f <Dockerfile name>`. I also have updated the README file with the correct command.
